### ISSUE TITLE
Add close method to font

### ISSUE THREAD

**Issue by benkiel** [robotools/defcon#222]
See notes in #220

**Comment by anthrotype** [comment]
After https://github.com/robotools/defcon/pull/220 was merged, the Windows tests started to fail. We cannot make a new defcon release until that's fixed. The last release was November 2018.

The problem is the `tearDownTestFontCopy` method is calling `os.remove` on a file which is locked by Windows because another process (i.e. us) still has a reference to it. That's how windows works, so we need to release that resource before calling remove.

While a `Font` instance exists, it has a reference to an open `UFOReader` which in turn has a reference to an open `FS` object; until the latter is closed, one cannot call os.remove on the UFO path on Windows.

I suggest we add a `close` method to `Font` class that calls `self._reader.close()`. And also `__enter__` and `__exit__` methods so `Font` objects work in `with Font(...) as font: ...` blocks, autoclosing themselves as the context is exited.

And then we should make sure to close any font before the tests call `tearDownTestFontCopy`.

I am not able to work on this right now, but i'd be happy to review a PR.

**Comment by benkiel** [comment]
Agree to the solution. I don't know if I'll have time this week to work on it, but I'll try. If not, next week and I'll PR it for review. Thank you for reminding me about this.

**Comment by anthrotype** [comment]
today I tried to have a look at this but I realized that the way the `testForExternalChanges` is done in defcon is irrimediably incompatible with the way ZipFS and zip files work.

It is not possible to have some external process -- or even the same process but different ZipFS class -- modify the same zip file that is currently being held open by a ZipFS object (the `fs` class used internally by fontTools UFOReader) without also corrupting the file, making it impossible for the original ZipFS object to read from it. If the data has already been read by the time the external process has overwritten the zip file that was held open, then it is too late and the modification is not seen.

The ZipFS in read-only (default) mode will seek and unzip specific sub-files to a temporary filesystem, lazily; this unzipping only occurs once per sub-file.
When opening a ZipFile for writing, the destination path is cleared, truncated; any existing references to that file in other ZipFS objects is thus invalidated (unless the contents of the zip file have been fully unzipped by that time).

I don't have a solution right now.

**Comment by benkiel** [comment]
(apologies for letting this linger too long, my promise above was `false`!)

Possible that the solution is to say that one can not keep open the zip file? i.e., it must be wholly consumed & file closed.

**Comment by anthrotype** [comment]
I see you tagged a new release. However, as far as I can tell, the issue I have outlined [in my previous comment](https://github.com/robotools/defcon/issues/222#issuecomment-500468873) is still outstanding.

**Comment by benkiel** [comment]
Yes, I haven't had the chance to wrap my head around that. Currently this just affects Windows, and having a tag with a couple more notifications and a change to `Glyph.notifications` was important for other tools. Yes, this isn't ideal.

**Comment by benkiel** [comment]
Feel free to pull down the release, if it's going to be an issue.

**Comment by anthrotype** [comment]
I see. But the issue is not only Windows-specific. It shows up in Windows because the latter blows up when some file is already opened and one tries to modify or remove it, whereas other OSes let you do that. But the problem is still there. Either the zip file has already been fully unzipped before the external changes overwrite the file -- in which case the original ZipFS object doesn't see these changes, unless a new ZipFile is reopened -- or if it hasn not been fully unzipped by the time the external changes occur (glyphs are parsed lazily in defcon) then the ZipFile will be corrupted.
At least that's what I remember from the time I looked into this. Unfortunately I don't have time to work on it right now.

**Comment by benkiel** [comment]
@anthrotype I've removed the tag and pypi release.

**Comment by benkiel** [comment]
Fixed in #269
